runtime: python27               # The name of the runtime environment that is used by your app.
threadsafe: true                # Configures your application to use concurrent requests.
api_version: 1                  # Version of the API in the given runtime environment that is used by your app.

instance_class: F1              # The instance class for this service, such as F1, F2, F4, F4_1G.
service: home                   # Name of service, such as Billing, Product, etc.

handlers:
- url: /.*
  script: main.app

inbound_services:
- warmup                        # Setup warmup request.

automatic_scaling:
  target_cpu_utilization: 0.65  # CPU utilization threshold for auto scalling a new instances. Input 0.5-0.95, the default is 0.6.
  min_instances: 5              # Minimum number of instances between 0-1000, value 0 to scaling to 0 instances to lower costs.
  max_instances: 100            # Maximum number of instances between 0-2147483647, where zero disables the setting.
  min_pending_latency: 30ms     # Request will wait in the pending queue and App Engine will try to reuse an existing instance.
  max_pending_latency: 1s       # When this threshold is reached, it is a signal to scale up a new instances.

# basic_scaling:
#  max_instances: 11
#  idle_timeout: 10m            # The instance will be shut down this amount of time after receiving its last request.

# manual_scaling:
#  instances: 5

# service_account:[SERVICE_ACCOUNT_NAME]@[PROJECT_ID].iam.gserviceaccount.com